notifications:
  email:
    on_success: change
    on_failure: change
language: php
php:
  - "7.2"
node_js:
    - "iojs"
    - "7"
addons:
  postgresql: "9.3"
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start
 - git clone git://github.com/moodle/moodle ../moodle && cd ../moodle
 - sudo apt-get update > /dev/null
 - travis_retry composer install
 - mv ../moodle-block_admin_presets blocks/admin_presets
 - cp config-dist.php config.php
 - sh -c "sed -i -e s/'password'/''/ -e s/example.com/localhost/ -e s%192.168.1.250%localhost% -e s%127.0.0.1/moodle%localhost:8000% -e s%/home/example%$HOME% -e 's%\(\$CFG.*bht\)%\n\1%' -e 's%\(\$CFG.*behat_wwwroot.*http://localhost:8000\)%\n\1%' config.php"
 - psql -c 'create database moodle;' -U postgres
 - sed -i s/\'username\'/\'postgres\'/ config.php
 - cat config.php
 - mkdir -m777 $HOME/moodledata
 - php -S localhost:8000 2> /dev/null > /dev/null &
 - npm install -g grunt
 - npm install -g grunt-cli
 - npm install
script:
 - grunt gherkinlint
